@startuml

skinparam responseMessageBelowArrow true

Scheduler -> QuotesRestCrawler : crawl() every 10s
Quote.rest <- QuotesRestCrawler : request
Quote.rest -> QuotesRestCrawler : response
QuotesRestCrawler -> Scheduler : quote
Scheduler -> QuoteFlip : flip()
QuoteFlip -> Scheduler : inverted quote
Scheduler -> CountCharQuote : count()
Scheduler -> DAO : save()
@enduml

@startuml
Main -> SendQuote : send()
SendQuote -> DAO
DAO -> SendQuote : count, inverted quote
SendQuote -> http : count, inverted quote
@enduml