@startuml
Title "My service architecture"
skinparam {
  ArrowColor DarkSlateGray
  ActorBorderColor DarkSlateGray
  ActorBackgroundColor SteelBlue
  ActorFontColor DarkSlateGray
  ParticipantBorderColor DarkSlateGray
  ParticipantBackgroundColor SteelBlue
  ParticipantFontColor White
  DatabaseBorderColor DarkSlateGray
  DatabaseBackgroundColor SteelBlue
  LifeLineBorderColor DarkSlateGray
  LifeLineBackgroundColor SteelBlue
  CollectionsBorderColor DarkSlateGray
  CollectionsBackgroundColor RoyalBlue
}

class Controller

interface Flipper

class QuoteFlip

interface Counter

class CountCharQuote

class Quote

interface Saver

class DAO

class SendQuote

interface Sender

Flipper *-- Quote
Flipper <|-- QuoteFlip
Counter *-- Quote
Counter <|-- CountCharQuote
Saver *-- Quote
Saver <|-- DAO
Sender <|-- SendQuote
SendQuote *-- DAO
Controller o-- Sender
Controller o-- Flipper
Controller o-- Counter
Controller o-- Saver
Saver *-- CountCharQuote

@enduml