@startuml
Title "My service architecture"
skinparam {
  ArrowColor DarkSlateGray
  ActorBorderColor DarkSlateGray
  ActorBackgroundColor SteelBlue
  ActorFontColor DarkSlateGray
  ParticipantBorderColor DarkSlateGray
  ParticipantBackgroundColor SteelBlue
  ParticipantFontColor White
  DatabaseBorderColor DarkSlateGray
  DatabaseBackgroundColor SteelBlue
  LifeLineBorderColor DarkSlateGray
  LifeLineBackgroundColor SteelBlue
  CollectionsBorderColor DarkSlateGray
  CollectionsBackgroundColor RoyalBlue
}

class SimpleQuote

interface Quote


interface Flipper

class QuoteFlip

interface Counter

class CountCharQuote

interface Repository

class DAO

interface Controller

class SendQuote

interface Crawler

class QuotesRestCrawler

Crawler <|-- QuotesRestCrawler
Crawler *-- Quote
Quote <|-- SimpleQuote
Flipper *-- Quote
Flipper <|-- QuoteFlip
Counter *-- Quote
Counter <|-- CountCharQuote
Repository *-- Quote
Repository <|-- DAO
Controller *-- Quote
Controller <|-- SendQuote
Repository *-- Controller

@enduml